### ISSUE TITLE
Search not starting after using context menu

### ISSUE THREAD

**Issue by drv42** [ijkilchenko/Fuzbal#27]
When I press ctrl+v search is working, but when using context menu "paste" it's not working.

**Comment by ijkilchenko** [comment]
Could you clarify? You're trying to copy and paste some text (that you'd like to search for) into the search bar in Fuzbal and it's not working? I just tried it and it is working for me -- I must be misunderstanding something.

**Comment by drv42** [comment]
When I press ctrl+v on keyboard it's working. 
When I using right click on a mouse and press "paste" - search is not starting.
![default](https://cloud.githubusercontent.com/assets/7890964/18669243/bdfd0a54-7f42-11e6-8de0-00ed1beea4f7.png)

There is the video for a better explanation.
https://youtu.be/vJ40XhvS7RU

**Comment by ijkilchenko** [comment]
Oh! That's very interesting. You're right it's a bug. It's happening become the search is trigged on a key up, but not trigged on a paste action. I'll look into fixing it. Thanks!

**Comment by ijkilchenko** [comment]
Newest version fixes this issue. It was only a couple of lines change. :D
